### PR TITLE
Add ordered version of the operator

### PR DESCRIPTION
**Pull request by jaceksokol**

### CODE REVIEW

**Comment by pjfanning** [comment]
Thanks @jaceksokol -- since Akka's equivalent is ordered, we need the order support you're adding but we could also have a mapAsyncPartitionedUnordered or something like that too - so it's useful to support both ordered and unordered in the internal code.

**Comment by pjfanning** [comment]
Thanks @jaceksokol. The key remaining API question is whether to replace the bufferSize parameter with a perPartition paramteter like the Akka API. Or we can have both. But the key question is whether it is feasible to support controlling the parallelism per partition as well as the existing parallelism setting that applies to the full job.

**Comment by jaceksokol** [comment]
I don't see a point in processing elements in parallel within a partition. From my perspective processing elements sequentially per partition can speed up processing while preserving the order of messages for a key. Processing events per partition in parallel seems to be similar to processing elements in parallel without the notion of a partition and ordering. Am I missing something?

**Comment by pjfanning** [comment]
The perPartition is documented at https://doc.akka.io/docs/akka/current/stream/operators/Source-or-Flow/mapAsyncPartitioned.html

Maybe the value is more about buffering and when to apply back pressure than about the number of parallel events that can be processed for a partition value.

**Pull request merged**
